# Generated by Django 6.0.5 on 2026-08-06 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_alter_shift_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='code',
            field=models.CharField(blank=True, help_text='کد/شماره فنی دستگاه (جدا از نام)', max_length=100, verbose_name='کد دستگاه'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام دستگاه'),
        ),
        migrations.CreateModel(
            name='ProductionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='تاریخ شروع بازه')),
                ('date_to', models.DateField(verbose_name='تاریخ پایان بازه')),
                ('feed_tonnage', models.FloatField(default=0, verbose_name='تناژ ورودی (Feed)')),
                ('product_tonnage', models.FloatField(default=0, verbose_name='تناژ محصول/خروجی خط')),
                ('tailing_tonnage', models.FloatField(default=0, verbose_name='تناژ باطله')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات / ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_reports', to='machines.productionline', verbose_name='خط تولید')),
            ],
            options={
                'verbose_name': 'گزارش تولید',
                'verbose_name_plural': 'گزارش\u200cهای تولید',
                'ordering': ['-date_from', '-created_at'],
                'indexes': [models.Index(fields=['line', 'date_from'], name='machines_pr_line_id_9a1018_idx'), models.Index(fields=['line', 'date_to'], name='machines_pr_line_id_24c7ae_idx')],
            },
        ),
    ]
