# Generated by Django 6.0.5 on 2026-08-11 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0009_alter_productionreport_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionreport',
            name='batala_avalieh',
        ),
        migrations.RemoveField(
            model_name='productionreport',
            name='darsad_batale',
        ),
        migrations.RemoveField(
            model_name='productionreport',
            name='darsad_dane_dorosht',
        ),
        migrations.RemoveField(
            model_name='productionreport',
            name='darsad_jerime',
        ),
        migrations.RemoveField(
            model_name='productionreport',
            name='darsad_rotobat',
        ),
        migrations.RemoveField(
            model_name='productionreport',
            name='darsad_takhfif',
        ),
        migrations.AddField(
            model_name='productionreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_reports', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده'),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='inputs',
            field=models.JSONField(blank=True, default=dict, verbose_name='مقادیر ورودی'),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='outputs',
            field=models.JSONField(blank=True, default=dict, verbose_name='خروجی\u200cهای محاسبه\u200cشده'),
        ),
        migrations.CreateModel(
            name='FactoryAnalysisDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('factory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factory_analysis_definition', to='machines.factory', verbose_name='کارخانه')),
            ],
            options={
                'verbose_name': 'تعریف آنالیز کارخانه',
                'verbose_name_plural': 'تعریف\u200cهای آنالیز کارخانه',
            },
        ),
        migrations.CreateModel(
            name='FactoryAnalysisInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, verbose_name='کلید (Key)')),
                ('name', models.CharField(max_length=100, verbose_name='نام نمایشی')),
                ('input_type', models.CharField(choices=[('number', 'عدد (Number)'), ('text', 'متن (Text)')], default='number', max_length=20, verbose_name='نوع ورودی')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='واحد اندازه\u200cگیری')),
                ('required', models.BooleanField(default=True, verbose_name='الزامی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='machines.factoryanalysisdefinition', verbose_name='تعریف آنالیز کارخانه')),
            ],
            options={
                'verbose_name': 'ورودی آنالیز کارخانه',
                'verbose_name_plural': 'ورودی\u200cهای آنالیز کارخانه',
                'ordering': ['definition', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('definition', 'key'), name='uniq_factory_input_key_per_def')],
            },
        ),
        migrations.CreateModel(
            name='FactoryAnalysisOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, verbose_name='کلید (Key)')),
                ('name', models.CharField(max_length=100, verbose_name='نام نمایشی')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='واحد اندازه\u200cگیری')),
                ('formula', models.TextField(verbose_name='فرمول')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='machines.factoryanalysisdefinition', verbose_name='تعریف آنالیز کارخانه')),
            ],
            options={
                'verbose_name': 'خروجی آنالیز کارخانه',
                'verbose_name_plural': 'خروجی\u200cهای آنالیز کارخانه',
                'ordering': ['definition', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('definition', 'key'), name='uniq_factory_output_key_per_def')],
            },
        ),
    ]
