# Generated by Django 6.0.5 on 2026-08-11 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0010_remove_productionreport_batala_avalieh_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveredTonnageDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tonnage_definition', to='machines.productionline', verbose_name='خط تولید')),
            ],
            options={
                'verbose_name': 'تعریف تناژ تحویلی خط',
                'verbose_name_plural': 'تعریف\u200cهای تناژ تحویلی خط',
            },
        ),
        migrations.CreateModel(
            name='DeliveredTonnage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='تاریخ تحویل')),
                ('hour', models.TimeField(verbose_name='ساعت تحویل')),
                ('inputs', models.JSONField(blank=True, default=dict, verbose_name='مقادیر ورودی')),
                ('outputs', models.JSONField(blank=True, default=dict, verbose_name='خروجی\u200cهای محاسبه\u200cشده')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات / ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tonnage_records', to='machines.contractor', verbose_name='پیمانکار')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tonnage_records', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tonnage_records', to='machines.productionline', verbose_name='خط تولید')),
            ],
            options={
                'verbose_name': 'ثبت تناژ تحویلی',
                'verbose_name_plural': 'ثبت\u200cهای تناژ تحویلی',
                'ordering': ['-date', '-hour', '-created_at'],
                'indexes': [models.Index(fields=['line', 'date'], name='machines_de_line_id_3cb256_idx'), models.Index(fields=['contractor'], name='machines_de_contrac_a8261d_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeliveredTonnageInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, verbose_name='کلید (Key)')),
                ('name', models.CharField(max_length=100, verbose_name='نام نمایشی')),
                ('input_type', models.CharField(choices=[('number', 'عدد (Number)'), ('text', 'متن (Text)')], default='number', max_length=20, verbose_name='نوع ورودی')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='واحد اندازه\u200cگیری')),
                ('required', models.BooleanField(default=True, verbose_name='الزامی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='machines.deliveredtonnagedefinition', verbose_name='تعریف تناژ تحویلی')),
            ],
            options={
                'verbose_name': 'ورودی تناژ تحویلی',
                'verbose_name_plural': 'ورودی\u200cهای تناژ تحویلی',
                'ordering': ['definition', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('definition', 'key'), name='uniq_tonnage_input_key_per_def')],
            },
        ),
        migrations.CreateModel(
            name='DeliveredTonnageOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, verbose_name='کلید (Key)')),
                ('name', models.CharField(max_length=100, verbose_name='نام نمایشی')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='واحد اندازه\u200cگیری')),
                ('formula', models.TextField(verbose_name='فرمول')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='machines.deliveredtonnagedefinition', verbose_name='تعریف تناژ تحویلی')),
            ],
            options={
                'verbose_name': 'خروجی تناژ تحویلی',
                'verbose_name_plural': 'خروجی\u200cهای تناژ تحویلی',
                'ordering': ['definition', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('definition', 'key'), name='uniq_tonnage_output_key_per_def')],
            },
        ),
    ]
