# Generated by Django 5.2.16 on 2026-09-26 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0014_shift_line'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, verbose_name='کلید (Key)')),
                ('name', models.CharField(max_length=100, verbose_name='نام تب')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('record_type', models.CharField(choices=[('range', 'بازه تاریخی (از تاریخ تا تاریخ)'), ('daily', 'روزانه (چند رکورد در روز با ساعت)')], default='range', max_length=20, verbose_name='نوع ثبت رکورد')),
                ('require_line', models.BooleanField(default=True, verbose_name='خط تولید الزامی است')),
                ('contractor_required', models.BooleanField(default=False, verbose_name='انتخاب پیمانکار الزامی است')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_tabs', to='machines.factory', verbose_name='کارخانه')),
            ],
            options={
                'verbose_name': 'تب کارخانه',
                'verbose_name_plural': 'تب\u200cهای کارخانه',
                'ordering': ['factory', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FactoryTabInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, verbose_name='کلید (Key)')),
                ('name', models.CharField(max_length=100, verbose_name='نام نمایشی')),
                ('input_type', models.CharField(choices=[('number', 'عدد (Number)'), ('text', 'متن (Text)')], default='number', max_length=20, verbose_name='نوع ورودی')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='واحد اندازه\u200cگیری')),
                ('required', models.BooleanField(default=True, verbose_name='الزامی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='machines.factorytab', verbose_name='تب')),
            ],
            options={
                'verbose_name': 'ورودی تب',
                'verbose_name_plural': 'ورودی\u200cهای تب',
                'ordering': ['tab', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FactoryTabOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, verbose_name='کلید (Key)')),
                ('name', models.CharField(max_length=100, verbose_name='نام نمایشی')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='واحد اندازه\u200cگیری')),
                ('formula', models.TextField(verbose_name='فرمول')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='machines.factorytab', verbose_name='تب')),
            ],
            options={
                'verbose_name': 'خروجی تب',
                'verbose_name_plural': 'خروجی\u200cهای تب',
                'ordering': ['tab', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FactoryTabRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(db_index=True, verbose_name='تاریخ شروع')),
                ('date_to', models.DateField(verbose_name='تاریخ پایان')),
                ('hour', models.TimeField(blank=True, null=True, verbose_name='ساعت ثبت')),
                ('inputs', models.JSONField(blank=True, default=dict, verbose_name='مقادیر ورودی')),
                ('outputs', models.JSONField(blank=True, default=dict, verbose_name='خروجی\u200cهای محاسبه\u200cشده')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات / ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tab_records', to='machines.contractor', verbose_name='پیمانکار')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tab_records', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tab_records', to='machines.productionline', verbose_name='خط تولید')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='machines.factorytab', verbose_name='تب')),
            ],
            options={
                'verbose_name': 'رکورد تب',
                'verbose_name_plural': 'رکوردهای تب',
                'ordering': ['-date_from', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='factorytab',
            constraint=models.UniqueConstraint(fields=('factory', 'key'), name='uniq_tab_key_per_factory'),
        ),
        migrations.AddConstraint(
            model_name='factorytabinput',
            constraint=models.UniqueConstraint(fields=('tab', 'key'), name='uniq_tab_input_key_per_tab'),
        ),
        migrations.AddConstraint(
            model_name='factorytaboutput',
            constraint=models.UniqueConstraint(fields=('tab', 'key'), name='uniq_tab_output_key_per_tab'),
        ),
        migrations.AddIndex(
            model_name='factorytabrecord',
            index=models.Index(fields=['tab', 'date_from'], name='machines_fa_tab_id_afe892_idx'),
        ),
        migrations.AddIndex(
            model_name='factorytabrecord',
            index=models.Index(fields=['tab', 'date_to'], name='machines_fa_tab_id_82092f_idx'),
        ),
        migrations.AddIndex(
            model_name='factorytabrecord',
            index=models.Index(fields=['line', 'date_from'], name='machines_fa_line_id_2ddcb3_idx'),
        ),
        migrations.AddIndex(
            model_name='factorytabrecord',
            index=models.Index(fields=['contractor'], name='machines_fa_contrac_7e6d14_idx'),
        ),
    ]
