# Generated by Django 5.2.16 on 2026-09-26 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0016_factorytabinput_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryTabReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام گزارش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض تب')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('filters', models.JSONField(blank=True, default=list, help_text='زیرمجموعه\u200cای از ["line", "contractor", "date_from", "date_to"] — خالی یعنی همه.', verbose_name='فیلترهای مجاز')),
                ('metrics', models.JSONField(blank=True, default=list, help_text='مثل [{"key": "recovery", "label": "بازیابی", "formula": "out.product__sum / out.feed__sum * 100"}]', verbose_name='متریک\u200cهای محاسباتی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='machines.factorytab', verbose_name='تب')),
            ],
            options={
                'verbose_name': 'گزارش تب',
                'verbose_name_plural': 'گزارش\u200cهای تب',
                'ordering': ['tab', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FactoryTabWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(max_length=20, verbose_name='نوع ویجت')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('config', models.JSONField(blank=True, default=dict, help_text='پارامترهای نوع ویجت (field/group_by/aggregation/...) — مستندات: TAB_REPORTS.md', verbose_name='تنظیمات')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='machines.factorytabreport', verbose_name='گزارش')),
            ],
            options={
                'verbose_name': 'ویجت گزارش',
                'verbose_name_plural': 'ویجت\u200cهای گزارش',
                'ordering': ['report', 'order', 'id'],
            },
        ),
    ]
