# Generated by Django 5.2.16 on 2026-09-27
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0018_factorytab_color_factorytab_icon'),
    ]

    operations = [
        migrations.DeleteModel(name='ActualAnalysis'),
        migrations.DeleteModel(name='AdditionalInputDefinition'),
        migrations.DeleteModel(name='AnalysisInputDefinition'),
        migrations.DeleteModel(name='AnalysisOutputDefinition'),
        migrations.DeleteModel(name='AnalysisPosition'),
        migrations.DeleteModel(name='AnalysisTypeDefinition'),
        migrations.DeleteModel(name='DeliveredTonnage'),
        migrations.DeleteModel(name='DeliveredTonnageInput'),
        migrations.DeleteModel(name='DeliveredTonnageOutput'),
        migrations.DeleteModel(name='DeliveredTonnageDefinition'),
        migrations.DeleteModel(name='FactoryAnalysisInput'),
        migrations.DeleteModel(name='FactoryAnalysisDefinition'),
        migrations.DeleteModel(name='FactoryAnalysisOutput'),
        migrations.DeleteModel(name='LineAnalysisDefinition'),
        migrations.DeleteModel(name='ProductionReport'),
    ]
