# Generated by Django 5.2.17 on 2026-09-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0019_remove_additionalinputdefinition_line_definition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorytabrecord',
            name='linked_records',
            field=models.JSONField(blank=True, default=dict, help_text='نگاشت کلید تب (زیرخط\u200cدار) به شناسه رکورد، مثلا {"mega_tonnage": 123} — خالی یعنی میانگین هم\u200cبازه', verbose_name='رکوردهای مرجع بین\u200cتبی'),
        ),
    ]
