# Generated by Django 6.0.5 on 2026-05-29 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="نام ویژگی"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="واحد اندازه\u200cگیری"
                    ),
                ),
            ],
            options={
                "verbose_name": "ویژگی فنی",
                "verbose_name_plural": "ویژگی\u200cهای فنی",
            },
        ),
        migrations.CreateModel(
            name="Factory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام کارخانه")),
                ("address", models.TextField(blank=True, verbose_name="آدرس")),
            ],
            options={
                "verbose_name": "کارخانه",
                "verbose_name_plural": "کارخانه\u200cها",
            },
        ),
        migrations.CreateModel(
            name="FailureReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان خرابی")),
            ],
            options={
                "verbose_name": "علت خرابی مرجع",
                "verbose_name_plural": "لیست علل خرابی",
            },
        ),
        migrations.CreateModel(
            name="ProductionLineAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="نام ویژگی خط تولید"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="واحد اندازه\u200cگیری"
                    ),
                ),
            ],
            options={
                "verbose_name": "ویژگی فنی خط تولید",
                "verbose_name_plural": "ویژگی\u200cهای فنی خط تولید",
            },
        ),
        migrations.CreateModel(
            name="DeviceTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام مدل/تیپ دستگاه"),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "available_attributes",
                    models.ManyToManyField(
                        to="machines.attribute",
                        verbose_name="ویژگی\u200cهای مورد نیاز این مدل",
                    ),
                ),
            ],
            options={
                "verbose_name": "الگوی دستگاه",
                "verbose_name_plural": "الگوهای دستگاه",
            },
        ),
        migrations.CreateModel(
            name="ProductionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام خط تولید")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="توضیحات خط تولید"),
                ),
                (
                    "attributes_values",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='مثال: {"ظرفیت": 1500, "طول": 75}',
                        null=True,
                        verbose_name="مقادیر ویژگی\u200cهای فنی خط",
                    ),
                ),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="machines.factory",
                        verbose_name="کارخانه مربوطه",
                    ),
                ),
            ],
            options={
                "verbose_name": "خط تولید",
                "verbose_name_plural": "خطوط تولید",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="نام/کد دستگاه"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب در خط"),
                ),
                (
                    "attributes_values",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="مقادیر ویژگی\u200cهای فنی",
                    ),
                ),
                (
                    "is_analyzer",
                    models.BooleanField(
                        default=False, verbose_name="آیا آنالیزور است؟"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="machines.devicetemplate",
                        verbose_name="الگوی مدل",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="machines.productionline",
                        verbose_name="خط تولید",
                    ),
                ),
            ],
            options={
                "verbose_name": "دستگاه",
                "verbose_name_plural": "دستگاه\u200cها",
                "ordering": ["line", "order"],
            },
        ),
        migrations.CreateModel(
            name="ProductionLineTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="نام مدل/تیپ خط تولید"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "available_attributes",
                    models.ManyToManyField(
                        to="machines.productionlineattribute",
                        verbose_name="ویژگی\u200cهای مورد نیاز این خط",
                    ),
                ),
            ],
            options={
                "verbose_name": "الگوی خط تولید",
                "verbose_name_plural": "الگوهای خط تولید",
            },
        ),
        migrations.AddField(
            model_name="productionline",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="machines.productionlinetemplate",
                verbose_name="الگوی خط",
            ),
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام شیفت")),
                ("start_time", models.TimeField(verbose_name="ساعت شروع")),
                ("end_time", models.TimeField(verbose_name="ساعت پایان")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="machines.factory",
                        verbose_name="کارخانه",
                    ),
                ),
            ],
            options={
                "verbose_name": "شیفت کاری",
                "verbose_name_plural": "شیفت\u200cهای کاری",
                "ordering": ["factory", "start_time"],
                "unique_together": {("factory", "name")},
            },
        ),
        migrations.CreateModel(
            name="DeviceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ گزارش")),
                (
                    "runtime_hours",
                    models.FloatField(default=0, verbose_name="ساعت کارکرد خط"),
                ),
                (
                    "downtime_hours",
                    models.FloatField(default=0, verbose_name="ساعت خرابی/توقف"),
                ),
                (
                    "failure_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="توضیحات تکمیلی خرابی"
                    ),
                ),
                (
                    "repair_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="شرح اقدامات/تعمیرات"
                    ),
                ),
                (
                    "feed_tonnage",
                    models.FloatField(default=0, verbose_name="تناژ ورودی (Feed)"),
                ),
                (
                    "product_tonnage",
                    models.FloatField(default=0, verbose_name="تناژ محصول/خروجی خط"),
                ),
                (
                    "tailing_tonnage",
                    models.FloatField(default=0, verbose_name="تناژ باطله"),
                ),
                (
                    "efficiency",
                    models.FloatField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="بهره\u200cوری/راندمان (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        help_text="اختیاری: اگر خرابی مربوط به دستگاه خاصی است",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="machines.device",
                        verbose_name="دستگاه خراب/مورد نظر",
                    ),
                ),
                (
                    "failure_cause",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="machines.failurereason",
                        verbose_name="علت خرابی (سیستمی)",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="machines.productionline",
                        verbose_name="خط تولید",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device_logs",
                        to="machines.shift",
                        verbose_name="شیفت",
                    ),
                ),
            ],
            options={
                "verbose_name": "گزارش عملکرد روزانه",
                "verbose_name_plural": "گزارشات عملکرد روزانه",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DeviceDailyAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ آنالیز")),
                (
                    "analysis_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="شرح/نتیجه آنالیز"
                    ),
                ),
                (
                    "value_1",
                    models.FloatField(blank=True, null=True, verbose_name="پارامتر ۱"),
                ),
                (
                    "value_2",
                    models.FloatField(blank=True, null=True, verbose_name="پارامتر ۲"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_analyses",
                        to="machines.device",
                        verbose_name="دستگاه (آنالیزور)",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_analyses",
                        to="machines.shift",
                        verbose_name="شیفت",
                    ),
                ),
            ],
            options={
                "verbose_name": "آنالیز روزانه دستگاه",
                "verbose_name_plural": "آنالیزهای روزانه دستگاه",
                "ordering": ["-date", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("device", "date", "shift"),
                        name="uniq_device_daily_analysis_per_day_shift",
                    )
                ],
            },
        ),
    ]
