# Generated by Django 6.0.5 on 2026-05-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicetemplate",
            name="available_attributes",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="machines.attribute",
                verbose_name="ویژگی\u200cهای مورد نیاز این مدل",
            ),
        ),
    ]
