# Generated by Django 6.0.5 on 2026-07-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_alter_devicetemplate_available_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='devices/', verbose_name='تصویر دستگاه'),
        ),
        migrations.AddField(
            model_name='devicedailyanalysis',
            name='sample_point',
            field=models.CharField(blank=True, choices=[('feed', 'خوراک (Feed)'), ('tailing', 'باطله (Tailing)'), ('product', 'محصول نهایی (Product)')], max_length=20, null=True, verbose_name='نقطه نمونه\u200cبرداری'),
        ),
        migrations.AddField(
            model_name='productionline',
            name='line_type',
            field=models.CharField(choices=[('crushing', 'خردایش'), ('processing', 'فرآوری'), ('conveying', 'انتقال / نوار نقاله'), ('other', 'سایر')], default='crushing', max_length=20, verbose_name='نوع خط'),
        ),
    ]
