# Generated by Django 6.0.5 on 2026-07-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_device_image_devicedailyanalysis_sample_point_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicelog',
            name='efficiency',
        ),
        migrations.AlterField(
            model_name='device',
            name='attributes_values',
            field=models.JSONField(blank=True, default=dict, verbose_name='مقادیر ویژگی\u200cهای فنی'),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='date',
            field=models.DateField(db_index=True, verbose_name='تاریخ گزارش'),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='failure_description',
            field=models.TextField(blank=True, default='N/A', verbose_name='توضیحات تکمیلی خرابی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='repair_description',
            field=models.TextField(blank=True, default='', verbose_name='شرح اقدامات/تعمیرات'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicetemplate',
            name='available_attributes',
            field=models.ManyToManyField(blank=True, to='machines.attribute', verbose_name='ویژگی\u200cهای مورد نیاز این مدل'),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='attributes_values',
            field=models.JSONField(blank=True, default=dict, help_text='مثال: {"ظرفیت": 1500, "طول": 75}', verbose_name='مقادیر ویژگی\u200cهای فنی خط'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['line', 'is_analyzer'], name='machines_de_line_id_501ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='devicedailyanalysis',
            index=models.Index(fields=['date', 'device'], name='machines_de_date_4dcf25_idx'),
        ),
        migrations.AddIndex(
            model_name='devicelog',
            index=models.Index(fields=['line', 'date'], name='machines_de_line_id_723973_idx'),
        ),
        migrations.AddIndex(
            model_name='devicelog',
            index=models.Index(fields=['date', 'shift'], name='machines_de_date_e537e2_idx'),
        ),
        migrations.AddIndex(
            model_name='productionline',
            index=models.Index(fields=['factory', 'line_type'], name='machines_pr_factory_a5d1ea_idx'),
        ),
    ]
