# Generated by Django 6.0.5 on 2026-07-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_remove_devicelog_efficiency_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('factory', 'name'), name='uniq_shift_per_factory'),
        ),
    ]
