# Generated by Django 6.0.5 on 2026-08-10 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_device_code_alter_device_name_productionreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTypeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام تعریف نوع آنالیز')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
            ],
            options={
                'verbose_name': 'تعریف نوع آنالیز',
                'verbose_name_plural': 'تعریف\u200cهای نوع آنالیز',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام پیمانکار')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='نام مسئول')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='شماره تماس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractors', to='machines.factory', verbose_name='کارخانه')),
            ],
            options={
                'verbose_name': 'پیمانکار',
                'verbose_name_plural': 'پیمانکاران',
                'ordering': ['factory', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ActualAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='تاریخ آنالیز')),
                ('inputs', models.JSONField(blank=True, default=dict, verbose_name='مقادیر ورودی')),
                ('outputs', models.JSONField(blank=True, default=dict, verbose_name='خروجی\u200cهای محاسبه\u200cشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_actual_analyses', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actual_analyses', to='machines.productionline', verbose_name='خط تولید')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_analyses', to='machines.shift', verbose_name='شیفت')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_analyses', to='machines.contractor', verbose_name='پیمانکار')),
            ],
            options={
                'verbose_name': 'آنالیز واقعی',
                'verbose_name_plural': 'آنالیزهای واقعی',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LineAnalysisDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_required', models.BooleanField(default=True, verbose_name='انتخاب پیمانکار الزامی است')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_definition', to='machines.productionline', verbose_name='خط تولید')),
            ],
            options={
                'verbose_name': 'تعریف آنالیز خط',
                'verbose_name_plural': 'تعریف\u200cهای آنالیز خط',
            },
        ),
        migrations.CreateModel(
            name='AnalysisOutputDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, verbose_name='کلید (Key)')),
                ('name', models.CharField(max_length=100, verbose_name='نام نمایشی')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='واحد اندازه\u200cگیری')),
                ('formula', models.TextField(help_text='مثال: product.fe / feed.fe * 100', verbose_name='فرمول')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('line_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='machines.lineanalysisdefinition', verbose_name='تعریف آنالیز خط')),
            ],
            options={
                'verbose_name': 'خروجی تعریف آنالیز',
                'verbose_name_plural': 'خروجی\u200cهای تعریف آنالیز',
                'ordering': ['line_definition', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalInputDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, verbose_name='کلید (Key)')),
                ('name', models.CharField(max_length=100, verbose_name='نام نمایشی')),
                ('input_type', models.CharField(choices=[('number', 'عدد (Number)'), ('text', 'متن (Text)')], default='number', max_length=20, verbose_name='نوع ورودی')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='واحد اندازه\u200cگیری')),
                ('required', models.BooleanField(default=True, verbose_name='الزامی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('line_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_inputs', to='machines.lineanalysisdefinition', verbose_name='تعریف آنالیز خط')),
            ],
            options={
                'verbose_name': 'ورودی اضافه خط',
                'verbose_name_plural': 'ورودی\u200cهای اضافه خط',
                'ordering': ['line_definition', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام موقعیت')),
                ('key', models.SlugField(max_length=60, verbose_name='کلید (Key)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_positions', to='machines.productionline', verbose_name='خط تولید')),
                ('definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='machines.analysistypedefinition', verbose_name='تعریف نوع آنالیز')),
            ],
            options={
                'verbose_name': 'موقعیت آنالیز خط',
                'verbose_name_plural': 'موقعیت\u200cهای آنالیز خط',
                'ordering': ['line', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('line', 'key'), name='uniq_position_key_per_line')],
            },
        ),
        migrations.CreateModel(
            name='AnalysisInputDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, verbose_name='کلید (Key)')),
                ('name', models.CharField(max_length=100, verbose_name='نام نمایشی')),
                ('input_type', models.CharField(choices=[('number', 'عدد (Number)'), ('text', 'متن (Text)')], default='number', max_length=20, verbose_name='نوع ورودی')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='واحد اندازه\u200cگیری')),
                ('required', models.BooleanField(default=True, verbose_name='الزامی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='machines.analysistypedefinition', verbose_name='تعریف نوع')),
            ],
            options={
                'verbose_name': 'ورودی تعریف آنالیز',
                'verbose_name_plural': 'ورودی\u200cهای تعریف آنالیز',
                'ordering': ['definition', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('definition', 'key'), name='uniq_input_key_per_definition')],
            },
        ),
        migrations.AddConstraint(
            model_name='contractor',
            constraint=models.UniqueConstraint(fields=('factory', 'name'), name='uniq_contractor_per_factory'),
        ),
        migrations.AddIndex(
            model_name='actualanalysis',
            index=models.Index(fields=['line', 'date'], name='machines_ac_line_id_25e4c7_idx'),
        ),
        migrations.AddIndex(
            model_name='actualanalysis',
            index=models.Index(fields=['contractor'], name='machines_ac_contrac_926e42_idx'),
        ),
        migrations.AddConstraint(
            model_name='analysisoutputdefinition',
            constraint=models.UniqueConstraint(fields=('line_definition', 'key'), name='uniq_output_key_per_line_def'),
        ),
        migrations.AddConstraint(
            model_name='additionalinputdefinition',
            constraint=models.UniqueConstraint(fields=('line_definition', 'key'), name='uniq_add_input_key_per_line_def'),
        ),
    ]
