# Generated by Django 6.0.5 on 2026-08-10 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0008_actualanalysis_date_range'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionreport',
            options={'ordering': ['-date_from', '-created_at'], 'verbose_name': 'آنالیز خط تولید', 'verbose_name_plural': 'آنالیز خطوط تولید'},
        ),
        migrations.RemoveField(
            model_name='productionreport',
            name='feed_tonnage',
        ),
        migrations.RemoveField(
            model_name='productionreport',
            name='product_tonnage',
        ),
        migrations.RemoveField(
            model_name='productionreport',
            name='tailing_tonnage',
        ),
        migrations.AddField(
            model_name='productionreport',
            name='batala_avalieh',
            field=models.FloatField(default=0, verbose_name='باطله اولیه'),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_reports', to='machines.contractor', verbose_name='پیمانکار'),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='darsad_batale',
            field=models.FloatField(default=0, verbose_name='درصد باطله'),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='darsad_dane_dorosht',
            field=models.FloatField(default=0, verbose_name='درصد دانه درشت'),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='darsad_jerime',
            field=models.FloatField(default=0, verbose_name='درصد جریمه'),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='darsad_rotobat',
            field=models.FloatField(default=0, verbose_name='درصد رطوبت'),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='darsad_takhfif',
            field=models.FloatField(default=0, verbose_name='درصد تخفیف'),
        ),
    ]
