# Generated by Django 6.0.5 on 2026-08-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0011_deliveredtonnagedefinition_deliveredtonnage_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='devicedailyanalysis',
            name='machines_de_date_4dcf25_idx',
        ),
        migrations.RemoveConstraint(
            model_name='devicedailyanalysis',
            name='uniq_device_daily_analysis_per_day_shift',
        ),
        migrations.AlterModelOptions(
            name='devicelog',
            options={'ordering': ['-date'], 'verbose_name': 'توقف خط تولید', 'verbose_name_plural': 'توقفات خط تولید'},
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='machines_de_line_id_501ddd_idx',
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='date',
            field=models.DateField(db_index=True, verbose_name='تاریخ توقف'),
        ),
        migrations.RemoveField(
            model_name='device',
            name='is_analyzer',
        ),
        migrations.DeleteModel(
            name='DeviceDailyAnalysis',
        ),
    ]
