# Generated by Django 5.2.16 on 2026-09-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0015_factorytab_factorytabinput_factorytaboutput_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorytabinput',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='فقط برای نوع «انتخابی»: لیست گزینه\u200cها، مثل ["الف", "ب", "ج"]', verbose_name='گزینه\u200cها'),
        ),
        migrations.AlterField(
            model_name='factorytabinput',
            name='input_type',
            field=models.CharField(choices=[('number', 'عدد (Number)'), ('text', 'متن (Text)'), ('select', 'انتخابی (Select)')], default='number', max_length=20, verbose_name='نوع ورودی'),
        ),
    ]
