# Generated by Django 5.2.16 on 2026-09-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0017_factorytabreport_factorytabwidget'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorytab',
            name='color',
            field=models.CharField(choices=[('slate', 'slate'), ('orange', 'orange'), ('emerald', 'emerald'), ('violet', 'violet'), ('sky', 'sky'), ('rose', 'rose'), ('teal', 'teal'), ('amber', 'amber'), ('indigo', 'indigo'), ('lime', 'lime'), ('cyan', 'cyan'), ('fuchsia', 'fuchsia')], default='slate', max_length=20, verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='factorytab',
            name='icon',
            field=models.CharField(choices=[('layers', 'layers'), ('truck', 'truck'), ('gauge', 'gauge'), ('flask', 'flask'), ('activity', 'activity'), ('bar-chart', 'bar-chart'), ('trending-up', 'trending-up'), ('box', 'box'), ('clipboard-list', 'clipboard-list'), ('database', 'database'), ('filter', 'filter'), ('layers-3', 'layers-3'), ('pie-chart', 'pie-chart'), ('line-chart', 'line-chart'), ('package', 'package'), ('factory', 'factory'), ('scale', 'scale'), ('clock', 'clock'), ('map-pin', 'map-pin'), ('cpu', 'cpu'), ('wrench', 'wrench'), ('zap', 'zap'), ('droplet', 'droplet'), ('thermometer', 'thermometer'), ('settings', 'settings'), ('target', 'target'), ('grid', 'grid')], default='layers', max_length=30, verbose_name='آیکون'),
        ),
    ]
