# Generated by Django 6.0.5 on 2026-07-13 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0003_device_image_devicedailyanalysis_sample_point_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'ورود'), ('logout', 'خروج'), ('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف')], max_length=20, verbose_name='عملیات')),
                ('model_name', models.CharField(blank=True, max_length=60, verbose_name='مدل')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='شیء')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='machines.factory', verbose_name='کارخانه')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ فعالیت',
                'verbose_name_plural': 'لاگ\u200cهای فعالیت',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'ادمین'), ('manager', 'مدیر کارخانه'), ('operator', 'اپراتور')], default='operator', max_length=20, verbose_name='نقش')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='machines.factory', verbose_name='کارخانه')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل\u200cهای کاربران',
            },
        ),
    ]
