# Generated by Django 6.0.5 on 2026-08-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='مثلاً {"granted": ["logs.delete"], "denied": []}', verbose_name='دسترسی\u200cهای سفارشی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'مدیر سیستم (ادمین)'), ('manager', 'مدیر کارخانه'), ('operator', 'اپراتور'), ('viewer', 'بیننده (فقط مشاهده)')], default='operator', max_length=20, verbose_name='نقش'),
        ),
        migrations.CreateModel(
            name='RolePermissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'مدیر سیستم (ادمین)'), ('manager', 'مدیر کارخانه'), ('operator', 'اپراتور'), ('viewer', 'بیننده (فقط مشاهده)')], max_length=20, verbose_name='نقش')),
                ('permission', models.CharField(max_length=40, verbose_name='کد دسترسی')),
                ('enabled', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسترسی نقش',
                'verbose_name_plural': 'دسترسی\u200cهای نقش\u200cها',
                'constraints': [models.UniqueConstraint(fields=('role', 'permission'), name='uniq_role_permission')],
            },
        ),
    ]
